
import { Poppins, Fredoka } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-poppins",
});

const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  variable: "--font-fredoka",
});

export const metadata = {
  title: "RecruitMind: Personality Test & Behavior Analysis",
  description: "Generated by create next.js",
  icons: {
    icon: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css',
  },
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${fredoka.variable} antialiased`}
      >
         {/* Navbar */}
        <Navbar />

        {children}

        {/* Main content from page.tsx */}
        {/* <main className="min-h-screen">{children}</main> */}
        
        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
